=== tdsat/YaogUI/storage_presets.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
           targetNamespace="YaogUI"
           xmlns="YaogUI storage_presets.xsd"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Presets">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Preset" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:choice minOccurs="0" maxOccurs="unbounded">
                                <xs:element name="Kind" minOccurs="0" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element minOccurs="0" maxOccurs="unbounded" name="Label">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="None"/>
                                                        <xs:enumeration value="Wood"/>
                                                        <xs:enumeration value="WoodBlock"/>
                                                        <xs:enumeration value="Rock"/>
                                                        <xs:enumeration value="RockBlock"/>
                                                        <xs:enumeration value="Metal"/>
                                                        <xs:enumeration value="Plant"/>
                                                        <xs:enumeration value="PlantProduct"/>
                                                        <xs:enumeration value="Ingredient"/>
                                                        <xs:enumeration value="Meat"/>
                                                        <xs:enumeration value="Leather"/>
                                                        <xs:enumeration value="Cloth"/>
                                                        <xs:enumeration value="Bone"/>
                                                        <xs:enumeration value="Weapon"/>
                                                        <xs:enumeration value="FightFabao"/>
                                                        <xs:enumeration value="TreasureFabao"/>
                                                        <xs:enumeration value="Hat"/>
                                                        <xs:enumeration value="Clothes"/>
                                                        <xs:enumeration value="Trousers"/>
                                                        <xs:enumeration value="Food"/>
                                                        <xs:enumeration value="Drug"/>
                                                        <xs:enumeration value="Dan"/>
                                                        <xs:enumeration value="Spell"/>
                                                        <xs:enumeration value="Tool"/>
                                                        <xs:enumeration value="MetalBlock"/>
                                                        <xs:enumeration value="Esoterica"/>
                                                        <xs:enumeration value="LeftoverMaterial"/>
                                                        <xs:enumeration value="SpellPaper"/>
                                                        <xs:enumeration value="LingStone"/>
                                                        <xs:enumeration value="Garbage"/>
                                                        <xs:enumeration value="SoulCrystal"/>
                                                        <xs:enumeration value="Treasure"/>
                                                        <xs:enumeration value="Influence"/>
                                                        <xs:enumeration value="SPStuffCategories"/>
                                                        <xs:enumeration value="BambooBlock"/>
                                                        <xs:enumeration value="Cape"/>
                                                        <xs:enumeration value="Horse"/>
                                                        <xs:enumeration value="Other"/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:element>
                                        </xs:sequence>
                                        <xs:attribute name="name" type="xs:string"/>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element name="Tier" minOccurs="0">
                                    <xs:complexType>
                                        <xs:attribute name="min">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:float">
                                                    <xs:minInclusive value="1"/>
                                                    <xs:maxInclusive value="12"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:attribute>
                                        <xs:attribute name="max">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:float">
                                                    <xs:minInclusive value="1"/>
                                                    <xs:maxInclusive value="12"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:attribute>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element name="Quality">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element minOccurs="0" maxOccurs="unbounded" name="Label">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="Poor"/>
                                                        <xs:enumeration value="Common"/>
                                                        <xs:enumeration value="Excellent"/>
                                                        <xs:enumeration value="Exquisite"/>
                                                        <xs:enumeration value="None"/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:element>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element name="Elements" maxOccurs="1">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element minOccurs="0" maxOccurs="unbounded" name="Label">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="None"/>
                                                        <xs:enumeration value="Metal"/>
                                                        <xs:enumeration value="Wood"/>
                                                        <xs:enumeration value="Water"/>
                                                        <xs:enumeration value="Fire"/>
                                                        <xs:enumeration value="Earth"/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:element>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                            </xs:choice>
                        </xs:sequence>
                  
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="sort" type="xs:integer"/>
                        <xs:attribute name="priority">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Low"/>
                                    <xs:enumeration value="Normal"/>
                                    <xs:enumeration value="High"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="onlyFSItem" type="xs:boolean"/>
                        <xs:attribute name="CanSale" type="xs:boolean"/>
                        <xs:attribute name="onlyBigFish" type="xs:boolean"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== tdsat/YaogUI/default_presets.xml
<?xml version="1.0" encoding="utf-8"?>
<Presets xmlns="YaogUI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="YaogUI storage_presets.xsd">
    <Preset name="Outer Gear" CanSale="true" priority="Normal">
        <Kind name="Equipment">
            <Label>Weapon</Label>
            <Label>Cape</Label>
            <Label>Clothes</Label>
            <Label>Trousers</Label>
            <Label>Treasure</Label>
        </Kind>
    </Preset>
    <Preset name="Pills" priority="High" CanSale="true">
        <Kind name="Material">
            <Label>Drug</Label>
            <Label>Dan</Label>
        </Kind>
    </Preset>
    <Preset name="Hot Stuff" priority="High" CanSale="true">
        <Kind name="Practice">
            <Label>Rock</Label>
            <Label>RockBlock</Label>
            <Label>Metal</Label>
            <Label>Dan</Label>
            <Label>Food</Label>
            <Label>Ingredient</Label>
            <Label>FightFabao</Label>
            <Label>TreasureFabao</Label>
            <Label>Drug</Label>
            <Label>Bone</Label>
        </Kind>
        <Tier min="6"/>
        <Elements>
            <Label>Fire</Label>
        </Elements>
    </Preset>
    <Preset name="Talismans" priority="High">
        <Kind name="Practice">
            <Label>SpellPaper</Label>
            <Label>Spell</Label>
        </Kind>
    </Preset>
    <Preset name="Manuals" priority="High">
        <Kind>
            <Label>Esoterica</Label>
        </Kind>
    </Preset>

    <Preset name="Artifacts" priority="High" CanSale="true">
        <Kind>
            <Label>FightFabao</Label>
        </Kind>
    </Preset>
    <Preset name="Mounts" priority="High">
        <Kind>
            <Label>Horse</Label>
        </Kind>
    </Preset>
    <Preset name="Relics" priority="High" onlyFSItem="true">
    </Preset>
</Presets>

=== tdsat/YaogUI/storage_presets_sample.xml
<?xml version="1.0" encoding="utf-8"?>
<Presets xmlns="YaogUI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="YaogUI storage_presets.xsd">
    <Preset name="Everything" priority="High" onlyFSItem="false" CanSale="true" onlyBigFish="false"> <!--  Low Normal High -->
        <Tier min="0" max="12"/>
<!-- Kind nodes don't need to be grouped, it's just done here for convenience
 You can put all labels in one node-->
        <Kind name="None">
            <Label>Tool</Label>
            <Label>Garbage</Label>
            <Label>Other</Label>
        </Kind>
        <Kind name="Material">
            <Label>Wood</Label>
            <Label>WoodBlock</Label>
            <Label>Rock</Label>
            <Label>RockBlock</Label>
            <Label>Metal</Label>
            <Label>MetalBlock</Label>
            <Label>Plant</Label>
            <Label>PlantProduct</Label>
            <Label>LeftoverMaterial</Label>
            <Label>Leather</Label>
            <Label>Cloth</Label>
            <Label>Bone</Label>
        </Kind>
        <Kind name="Equipment">
            <Label>Weapon</Label>
            <Label>Cape</Label>
            <Label>Clothes</Label>
            <Label>Trousers</Label>
            <Label>Treasure</Label>
            <Label>Horse</Label>
        </Kind>
        <Kind name="Consumable">
            <Label>Food</Label>
            <Label>Meat</Label>
            <Label>Ingredient</Label>
            <Label>Drug</Label>
        </Kind>
        <Kind name="Practice">
            <Label>SpellPaper</Label>
            <Label>SoulCrystal</Label>
            <Label>Spell</Label>
            <Label>Dan</Label>
            <Label>LingStone</Label>
            <Label>Esoterica</Label>
            <Label>FightFabao</Label>
            <Label>TreasureFabao</Label>
        </Kind>
        <Quality>
            <Label>Poor</Label>
            <Label>Common</Label>
            <Label>Excellent</Label>
            <Label>Exquisite</Label>
            <Label>None</Label>
        </Quality>
        <Elements>
            <Label>None</Label>
            <Label>Metal</Label>
            <Label>Wood</Label>
            <Label>Water</Label>
            <Label>Fire</Label>
            <Label>Earth</Label>
        </Elements>
    </Preset>
</Presets>
